from .a_collect_url_home_all_category import collect_url_home_all_category_func
from .b_selection_category_to_scrap import selection_category_for_scrap_func
from .c_scrap_books_urls_in_category import scrap_books_urls_in_category_func
from .d_check_url_books import check_url_books_func
from .e_scrap_data import scrap_data_func
from .f_write_csv import write_data_desired_in_csv_func
from .g_cover_generate_path import cover_generate_path_func

from . import main_p02_scrap as main

from ._01_sleep_requests_re_attempt import requests_respectful as rq_resp
from ._02_defensive_n_responsive_download import defensif_n_responsive_ddl as def_ddl
